dist: xenial

language: minimal

services:
  - docker

jobs:
  include:
    - os: linux
      arch: amd64
      env:
        - IMAGE_REPO="linux-utils"
        - TRIVYARCH="64bit"
        - RELEASE_TAG_DOWNSTREAM=1
    - os: linux
      arch: arm64
      env:
        - IMAGE_REPO="linux-utils-arm64"
        - TRIVYARCH="ARM64"
        - RELEASE_TAG_DOWNSTREAM=0
    - os: linux
      arch: ppc64le
      env:
        - IMAGE_REPO="linux-utils-arm64"
        - TRIVYARCH="PPC64LE"
        - RELEASE_TAG_DOWNSTREAM=0

before_install:
  - if [ -z $IMAGE_ORG ]; then
      IMAGE_ORG="openebs";
      export IMAGE_ORG;
    fi
  - export DIMAGE="${IMAGE_ORG}/${IMAGE_REPO}"
  - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-${TRIVYARCH}.tar.gz
  - tar zxvf trivy_${VERSION}_Linux-${TRIVYARCH}.tar.gz

script:
  - make image
  - make test
  - ./trivy --exit-code 0 --severity HIGH --no-progress ${DIMAGE}:ci
  - ./trivy --exit-code 1 --severity CRITICAL --no-progress ${DIMAGE}:ci
  - make push
  # If this build is running due to travis release tag, and
  # this job indicates to push the release downstream, then
  # go ahead and tag the dependent repo.
  #
  # Convert the TRAVIS_TAG to the corresponding release branch.
  # $TRAVIS_BRANCH contains the same value as $TRAVIS_TAG.
  # Example: TRAVIS_TAG and TRAVIS_BRANCH will have v1.9.0-RC1, 
  # when github release tag is v1.9.0-RC1
  #
  # OpenEBS release are triggered from release branches that are named 
  # as v1.9.x or v1.9.x-hotfix or v1.9.x-custom  
  #
  # The tag to release branch conversion should be handled as follows:
  # v1.9.0-RC1 => should be v1.9.x
  # v1.9.0-hotfixid => should be v1.9.x-hotfixid
  # v1.9.0 => should be v1.9.x
  # v1.9.1 => should be v1.9.x
  # v1.9.0-custom-RC1 => should be v1.9.x-custom
  # v1.9.0-custom => should be v1.9.x-custom
  # v1.9.1-custom => should be v1.9.x-custom
  # 
  # Allow for building forked openebs pipelines. 
  # Tag the downstream repos under current repo org. 
  - if [ -z $REPO_ORG ]; then
      REPO_ORG=$(echo "$TRAVIS_REPO_SLUG" | cut -d'/' -f1);
      export REPO_ORG;
    fi
  - if [ ! -z $TRAVIS_TAG ] && [ $RELEASE_TAG_DOWNSTREAM = 1 ] && [ "$TRAVIS_REPO_SLUG" == "${REPO_ORG}/linux-utils" ]; then
      TAG_SUFFIX=$(echo "$TRAVIS_TAG" | cut -d'-' -f2);
      if [ "$TAG_SUFFIX" == "$TRAVIS_TAG" ] || [[ $TAG_SUFFIX =~ ^RC ]]; then 
        REL_SUFFIX="";
      else
        REL_SUFFIX="-$TAG_SUFFIX";
      fi;
      REL_BRANCH=$(echo $(echo "$TRAVIS_TAG" | cut -d'-' -f1 | rev | cut -d'.' -f2- | rev).x$REL_SUFFIX) ;
      ./buildscripts/git-release "${REPO_ORG}/jiva" "$TRAVIS_TAG" "$REL_BRANCH" || travis_terminate 1;
      ./buildscripts/git-release "${REPO_ORG}/libcstor" "$TRAVIS_TAG" "$REL_BRANCH" || travis_terminate 1;
    fi
